db:
  image: postgres:9.4
main:
  build: .
  ports:
    - "5000:5000"
  environment:
    - FLASK_ENV
    - DATABASE_CONNECTION_STRING
  volumes:
    - ./:/usr/src/app/
    - ./cfg/:/usr/src/app/cfg
  links:
    - db